"""empty message

Revision ID: 682431ce81f5
Revises: 3a8b6737fb92
Create Date: 2022-10-22 11:22:10.569854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682431ce81f5'
down_revision = '3a8b6737fb92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_records', sa.Column('profile', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_records', 'profile')
    # ### end Alembic commands ###
