"""empty message

Revision ID: 9c864c2374ae
Revises: 105ca12236d0
Create Date: 2022-10-23 06:13:35.129597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c864c2374ae'
down_revision = '105ca12236d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('member_records_email_key', 'member_records', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('member_records_email_key', 'member_records', ['email'])
    # ### end Alembic commands ###
